- name: take vars from prompt means enter values at run time
  hosts: web 
  vars_prompt:
    - name: COURSE
      prompt: please enter COURSE  
      private: false # entered values we can see, if we didn't give false entered values we can't see while entering 
                                                                                      #but while priniting we can see
    - name: DURATION
      prompt: Please enter DURATION
    - name: TRAINER
      prompt: Please enter TRAINER  
  tasks: 
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi, i am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"

